{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# BlackJack Game Code:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 1: Imports and Global Variables -\n",
    "import random\n",
    "suits = ('Hearts', 'Diamonds', 'Spades', 'Clubs')\n",
    "ranks = ('Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King','Ace')\n",
    "values = {'Two':2,'Three':3,'Four':4,'Five':5,'Six':6,'Seven':7,'Eight':8,\n",
    "         'Nine':9,'Ten':10,'Jack':10,'Queen':10,'King':10,'Ace':11}\n",
    "playing = True\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 2: Card class -\n",
    "class Card:\n",
    "    def __init__(self,rank,suit):\n",
    "        self.rank = rank\n",
    "        self.suit = suit\n",
    "    def __str__(self):\n",
    "        return self.rank + ' of ' + self.suit\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 3: Deck class -\n",
    "class Deck:\n",
    "    def __init__(self):\n",
    "        self.deck = []\n",
    "        for suit in suits:\n",
    "            for rank in ranks:\n",
    "                self.deck.append(Card(rank,suit))\n",
    "    def __str__(self):\n",
    "        deck_comp = ''\n",
    "        for card in self.deck:\n",
    "            deck_comp += '\\n' + card.__str__()\n",
    "        return 'The deck has: ' + deck_comp\n",
    "    def shuffle(self):\n",
    "        random.shuffle(self.deck)\n",
    "    def deal(self):\n",
    "        single_card = self.deck.pop()\n",
    "        return single_card"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The deck has: \n",
      "Six of Clubs\n",
      "King of Hearts\n",
      "Ten of Diamonds\n",
      "Nine of Hearts\n",
      "Nine of Spades\n",
      "Ace of Hearts\n",
      "Seven of Clubs\n",
      "Two of Clubs\n",
      "Six of Diamonds\n",
      "Eight of Hearts\n",
      "Jack of Hearts\n",
      "Queen of Diamonds\n",
      "Nine of Diamonds\n",
      "Five of Clubs\n",
      "Queen of Clubs\n",
      "Ten of Clubs\n",
      "Jack of Diamonds\n",
      "King of Spades\n",
      "Six of Spades\n",
      "Ace of Spades\n",
      "Ace of Diamonds\n",
      "Three of Clubs\n",
      "Two of Diamonds\n",
      "Eight of Spades\n",
      "Jack of Spades\n",
      "Jack of Clubs\n",
      "Seven of Spades\n",
      "King of Clubs\n",
      "Three of Diamonds\n",
      "Five of Diamonds\n",
      "Four of Hearts\n",
      "Nine of Clubs\n",
      "Three of Hearts\n",
      "Ten of Spades\n",
      "Ace of Clubs\n",
      "Four of Diamonds\n",
      "Queen of Hearts\n",
      "Seven of Hearts\n",
      "Five of Spades\n",
      "Eight of Clubs\n",
      "Four of Spades\n",
      "Four of Clubs\n",
      "Queen of Spades\n",
      "King of Diamonds\n",
      "Two of Hearts\n",
      "Three of Spades\n",
      "Ten of Hearts\n",
      "Seven of Diamonds\n",
      "Six of Hearts\n",
      "Two of Spades\n",
      "Eight of Diamonds\n",
      "Five of Hearts\n"
     ]
    }
   ],
   "source": [
    "test_deck = Deck()\n",
    "test_deck.shuffle()\n",
    "print(test_deck)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 4: Hand Class - \n",
    "class Hand:\n",
    "    def __init__(self):\n",
    "        self.cards = []\n",
    "        self.value = 0\n",
    "        self.aces = 0\n",
    "    def add_card(self,card):\n",
    "        self.cards.append(card)\n",
    "        self.value += values[card.rank]\n",
    "        if card.rank == 'Ace':\n",
    "            self.aces += 1\n",
    "    def adjust_for_ace(self):\n",
    "        while self.value > 21 and self.aces > 0:\n",
    "            self.value -= 10\n",
    "            self.aces -= 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Nine of Hearts\n",
      "9\n"
     ]
    }
   ],
   "source": [
    "test_deck = Deck()\n",
    "test_deck.shuffle()\n",
    "test_player = Hand()\n",
    "pulled_card = test_deck.deal()\n",
    "print(pulled_card)\n",
    "test_player.add_card(pulled_card)\n",
    "print(test_player.value)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 5: Chips Class -\n",
    "class Chips:\n",
    "    def __init__(self,total = 100):\n",
    "        self.total = 100\n",
    "        self.bet = 0\n",
    "    def win_bet(self):\n",
    "        self.total += self.bet\n",
    "    def lose_bet(self):\n",
    "        self.total -= self.bet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 6: Taking bets -\n",
    "def take_bet(chips):\n",
    "    while True:\n",
    "        try: \n",
    "            chips.bet = int(input('How many chips would you like to bet?: '))\n",
    "        except ValueError:\n",
    "            print('Sorry, please input an integer: ')\n",
    "        else:\n",
    "            if chips.bet > chips.total:\n",
    "                print(f'Sorry, you do not have enough chips. You only have: {chips.total}')\n",
    "            else:\n",
    "                break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 7: Taking hits -\n",
    "def hit(deck,hand):\n",
    "    single_card = deck.deal()\n",
    "    hand.add_card(single_card)\n",
    "    hand.adjust_for_ace()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 8: Hit or Stand? -\n",
    "def hit_or_stand(deck,hand):\n",
    "    global playing\n",
    "    while True:\n",
    "        x = input('Hit or Stand?: Enter h or s.')\n",
    "        if x[0].lower() == 'h':\n",
    "            hit(deck,hand)\n",
    "        elif x[0].lower() == 's':\n",
    "            print(\"Player Stands - Dealer's turn\")\n",
    "            playing = False\n",
    "        else:\n",
    "            print('Sorry, I did not understand that. Please enter h or s only.')\n",
    "            continue\n",
    "            \n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 9: Display cards -\n",
    "def show_some(player,dealer):\n",
    "    print(\"DEALER'S HAND:\")\n",
    "    print('one card hidden!')\n",
    "    print(dealer.cards[1])\n",
    "    print('\\n')\n",
    "    print('\\n')\n",
    "    print(\"PLAYER'S HAND:\")\n",
    "    for card in player.cards:\n",
    "        print(card)\n",
    "    print('\\n')\n",
    "    print('\\n')\n",
    "\n",
    "def show_all(player,dealer):\n",
    "    print(\"DEALER'S HAND:\")\n",
    "    for card in dealer.cards:\n",
    "        print(card)\n",
    "    print('\\n')\n",
    "    print('\\n')\n",
    "    print(\"PLAYER'S HAND:\")\n",
    "    for card in player.cards:\n",
    "        print(card)\n",
    "    print('\\n')\n",
    "    print('\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 10: End-of-game-scenarios -\n",
    "def player_busts(player,dealer,chips):\n",
    "    print('BUST PLAYER!')\n",
    "    chips.lose_bet()\n",
    "def player_wins(player,dealer,chips):\n",
    "    print('PLAYER WINS!')\n",
    "    chips.win_bet()\n",
    "def dealer_busts(player,dealer,chips):\n",
    "    print('PLAYER WINS! DEALER BUSTED!')\n",
    "    chips.win_bet()\n",
    "def dealer_wins(player,dealer,chips):\n",
    "    print('DEALER WINS!')\n",
    "    chips.lose_bet()\n",
    "def push():\n",
    "    print('Dealer and player tie! PUSH')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Welcome to BlackJack!\n",
      "How many chips would you like to bet?: 300\n",
      "Sorry, you do not have enough chips. You only have: 100\n",
      "How many chips would you like to bet?: 80\n",
      "DEALER'S HAND:\n",
      "one card hidden!\n",
      "Five of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Seven of Hearts\n",
      "Ten of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "Hit or Stand?: Enter h or s.s\n",
      "Player Stands - Dealer's turn\n",
      "DEALER'S HAND:\n",
      "one card hidden!\n",
      "Five of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Seven of Hearts\n",
      "Ten of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "DEALER'S HAND:\n",
      "Two of Clubs\n",
      "Five of Hearts\n",
      "Six of Diamonds\n",
      "Ace of Diamonds\n",
      "Jack of Diamonds\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Seven of Hearts\n",
      "Ten of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER WINS! DEALER BUSTED!\n",
      "\n",
      " Player's total chips are at: 180\n",
      "Would you like to play again?: y/n y\n",
      "Welcome to BlackJack!\n",
      "How many chips would you like to bet?: 300\n",
      "Sorry, you do not have enough chips. You only have: 100\n",
      "How many chips would you like to bet?: 80\n",
      "DEALER'S HAND:\n",
      "one card hidden!\n",
      "Eight of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Seven of Clubs\n",
      "King of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "Hit or Stand?: Enter h or s.s\n",
      "Player Stands - Dealer's turn\n",
      "DEALER'S HAND:\n",
      "one card hidden!\n",
      "Eight of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Seven of Clubs\n",
      "King of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "DEALER'S HAND:\n",
      "Jack of Diamonds\n",
      "Eight of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Seven of Clubs\n",
      "King of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "DEALER WINS!\n",
      "\n",
      " Player's total chips are at: 20\n",
      "Would you like to play again?: y/n y\n",
      "Welcome to BlackJack!\n",
      "How many chips would you like to bet?: 80\n",
      "DEALER'S HAND:\n",
      "one card hidden!\n",
      "Seven of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Two of Hearts\n",
      "Three of Spades\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "Hit or Stand?: Enter h or s.h\n",
      "DEALER'S HAND:\n",
      "one card hidden!\n",
      "Seven of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Two of Hearts\n",
      "Three of Spades\n",
      "Seven of Clubs\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "DEALER'S HAND:\n",
      "Nine of Spades\n",
      "Seven of Hearts\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "PLAYER'S HAND:\n",
      "Two of Hearts\n",
      "Three of Spades\n",
      "Seven of Clubs\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "DEALER WINS!\n",
      "\n",
      " Player's total chips are at: 20\n"
     ]
    }
   ],
   "source": [
    "# Step 11: Game Logic -\n",
    "while True:\n",
    "    # Print opening statement:\n",
    "    \n",
    "    print('Welcome to BlackJack!')\n",
    "    \n",
    "    # Create + shuffle deck + deal two cards to each player:\n",
    "    deck = Deck()\n",
    "    deck.shuffle()\n",
    "    \n",
    "    player_hand = Hand()\n",
    "    player_hand.add_card(deck.deal())\n",
    "    player_hand.add_card(deck.deal())\n",
    "    \n",
    "    dealer_hand = Hand()\n",
    "    dealer_hand.add_card(deck.deal())\n",
    "    dealer_hand.add_card(deck.deal())\n",
    "    \n",
    "    # Set up the player's chips:\n",
    "    player_chips = Chips()\n",
    "    \n",
    "    # Prompt player for bet:\n",
    "    take_bet(player_chips)\n",
    "    \n",
    "    # Show cards (keep one dealer card hidden):\n",
    "    show_some(player_hand,dealer_hand)\n",
    "    \n",
    "    while playing:\n",
    "        # Prompt for player to hit or stand:\n",
    "        hit_or_stand(deck,player_hand)\n",
    "        \n",
    "        # Show cards (but keep one dealer card hidden):\n",
    "        show_some(player_hand,dealer_hand)\n",
    "        \n",
    "        # If player_hand > 21, run player_busts() and break out of loop:\n",
    "        if player_hand.value > 21:\n",
    "            player_busts(player_hand,dealer_hand,player_chips)\n",
    "            break\n",
    "            \n",
    "        # If player hasn't busted, player dealer's hand:\n",
    "        if player_hand.value <= 21:\n",
    "            while dealer_hand.value < player_hand.value:\n",
    "                hit(deck,dealer_hand)\n",
    "            \n",
    "            # Show all cards:\n",
    "            show_all(player_hand,dealer_hand)\n",
    "            \n",
    "            # Run different winning scenarios:\n",
    "            if dealer_hand.value > 21:\n",
    "                dealer_busts(player_hand,dealer_hand,player_chips)\n",
    "            elif dealer_hand.value > player_hand.value:\n",
    "                dealer_wins(player_hand,dealer_hand,player_chips)\n",
    "            elif dealer_hand.value < player_hand.value:\n",
    "                player_wins(player_hand,dealer_hand,player_chips)\n",
    "            else:\n",
    "                push(player_hand,dealer_hand)\n",
    "        \n",
    "        # Inform player of chip total:\n",
    "        print(f\"\\n Player's total chips are at: {player_chips.total}\")\n",
    "        \n",
    "    # Ask to play again:\n",
    "    new_game = input('Would you like to play again?: y/n ')\n",
    "    if new_game[0].lower() == 'y':\n",
    "        playing = True\n",
    "        continue\n",
    "    else:\n",
    "        print('Thank you for playing BlackJack!')\n",
    "        break"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
